# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='No image', upload_to='photos/'),
        ),
    ]
